const rivenProperties = [{
    gvas: ['VectorGameStates', 'PlayerLocation', 'Value'],
    html: 'player-position',
    title: 'Player position',
    description: 'Stay relatively close to where you saved. This variable does not control what terrain is loaded, so you\'ll fall through the ground if you move too far.'

}, {
    gvas: ['RotatorGameStates', 'PlayerRotation', 'Value'],
    html: 'player-rotation',
    title: 'Player rotation'
}, {
    html: 'telescope-solution',
    title: 'Telescope Solution',
    children: [{
        gvas: ['IntGameStates', 'C116916F4877D735A418D2916F65B733', 'Value'],
        html: 'telescope-solution-1',
        title: 'Digit 1',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', '93C1592A4D719CB404CCA5810798FC26', 'Value'],
        html: 'telescope-solution-2',
        title: 'Digit 2',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', 'E5B348FD453245493FD4B38C6B46BEA8', 'Value'],
        html: 'telescope-solution-3',
        title: 'Digit 3',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', '818975CF4A6364CDC451B99FE7C88E52', 'Value'],
        html: 'telescope-solution-4',
        title: 'Digit 4',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', 'B674A7294B3207EB744C0DA03971446A', 'Value'],
        html: 'telescope-solution-5',
        title: 'Digit 5',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', '3E823B5F40A18302191E0D83280C683C', 'Value'],
        html: 'telescope-solution-6',
        title: 'Digit 6',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', 'B32BF0644C06B3421E351881FF6CE557', 'Value'],
        html: 'telescope-solution-7',
        title: 'Digit 7',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', '9B2E0ECA4C7071519EF5DABD682358D0', 'Value'],
        html: 'telescope-solution-8',
        title: 'Digit 8',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', '82328056403E25E44D9857B2DD05289C', 'Value'],
        html: 'telescope-solution-9',
        title: 'Digit 9',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }, {
        gvas: ['IntGameStates', '4D8246E643268E7B68ECF5BB8AC22E20', 'Value'],
        html: 'telescope-solution-10',
        title: 'Digit 10',
        type: 'dropdown',
        values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    }]
}, {
    html: 'animal-totems-solution',
    title: 'Animal Totems Solution',
    description: 'Stand in the very center of the circle and face the linking book. Index starts at 0 (whark) and increases clockwise. Exit is between 11 (moose) and 12 (alligator).',
    children: [{
        gvas: ['IntGameStates', '261D18FE4FF7B3A0E9FC16B2C9F09C58', 'Value'],
        html: 'animal-totems-solution-1',
        title: 'Stone 1',
        type: 'dropdown',
        values: [
            { actual: 0, display: 'Whark (0)' },
            { actual: 1, display: 'Ardvark? (1)' },
            { actual: 2, display: 'Mole (2)' },
            { actual: 3, display: 'Sunner (3)' },
            { actual: 4, display: 'Flying Beetle (4)' },
            { actual: 5, display: 'Gaping Fish (5)' },
            { actual: 6, display: 'Anteater (6)' },
            { actual: 7, display: 'Ostrich (7)' },
            { actual: 8, display: 'Tadpole (8)' },
            { actual: 9, display: 'Stork (9)' },
            { actual: 10, display: 'Beetle (10)' },
            { actual: 11, display: 'Moose (11)' },
            { actual: 12, display: 'Alligator (12)' },
            { actual: 13, display: 'Toucan (13)' },
            { actual: 14, display: 'Boar (14)' },
            { actual: 15, display: 'Triangle Fish (15)' },
            { actual: 16, display: 'Praying Beetle (16)' },
            { actual: 17, display: 'Ytram (17)' },
            { actual: 18, display: 'Narwhal (18)' },
            { actual: 19, display: 'Pig (19)' },
            { actual: 20, display: 'Crab (20)' },
            { actual: 21, display: 'Flea (21)' },
            { actual: 22, display: 'Seahorse (22)' },
            { actual: 23, display: 'Shark (23)' }
        ]
    }, {
        gvas: ['IntGameStates', '5A1354B04B01F6D207C0A09AEB5EF662', 'Value'],
        html: 'animal-totems-solution-2',
        title: 'Stone 2',
        type: 'dropdown',
        values: [
            { actual: 0, display: 'Whark (0)' },
            { actual: 1, display: 'Ardvark? (1)' },
            { actual: 2, display: 'Mole (2)' },
            { actual: 3, display: 'Sunner (3)' },
            { actual: 4, display: 'Flying Beetle (4)' },
            { actual: 5, display: 'Gaping Fish (5)' },
            { actual: 6, display: 'Anteater (6)' },
            { actual: 7, display: 'Ostrich (7)' },
            { actual: 8, display: 'Tadpole (8)' },
            { actual: 9, display: 'Stork (9)' },
            { actual: 10, display: 'Beetle (10)' },
            { actual: 11, display: 'Moose (11)' },
            { actual: 12, display: 'Alligator (12)' },
            { actual: 13, display: 'Toucan (13)' },
            { actual: 14, display: 'Boar (14)' },
            { actual: 15, display: 'Triangle Fish (15)' },
            { actual: 16, display: 'Praying Beetle (16)' },
            { actual: 17, display: 'Ytram (17)' },
            { actual: 18, display: 'Narwhal (18)' },
            { actual: 19, display: 'Pig (19)' },
            { actual: 20, display: 'Crab (20)' },
            { actual: 21, display: 'Flea (21)' },
            { actual: 22, display: 'Seahorse (22)' },
            { actual: 23, display: 'Shark (23)' }
        ]
    }, {
        gvas: ['IntGameStates', 'DD60124E4CCE7A37545867A7E12C0E62', 'Value'],
        html: 'animal-totems-solution-3',
        title: 'Stone 3',
        type: 'dropdown',
        values: [
            { actual: 0, display: 'Whark (0)' },
            { actual: 1, display: 'Ardvark? (1)' },
            { actual: 2, display: 'Mole (2)' },
            { actual: 3, display: 'Sunner (3)' },
            { actual: 4, display: 'Flying Beetle (4)' },
            { actual: 5, display: 'Gaping Fish (5)' },
            { actual: 6, display: 'Anteater (6)' },
            { actual: 7, display: 'Ostrich (7)' },
            { actual: 8, display: 'Tadpole (8)' },
            { actual: 9, display: 'Stork (9)' },
            { actual: 10, display: 'Beetle (10)' },
            { actual: 11, display: 'Moose (11)' },
            { actual: 12, display: 'Alligator (12)' },
            { actual: 13, display: 'Toucan (13)' },
            { actual: 14, display: 'Boar (14)' },
            { actual: 15, display: 'Triangle Fish (15)' },
            { actual: 16, display: 'Praying Beetle (16)' },
            { actual: 17, display: 'Ytram (17)' },
            { actual: 18, display: 'Narwhal (18)' },
            { actual: 19, display: 'Pig (19)' },
            { actual: 20, display: 'Crab (20)' },
            { actual: 21, display: 'Flea (21)' },
            { actual: 22, display: 'Seahorse (22)' },
            { actual: 23, display: 'Shark (23)' }
        ]
    }, {
        gvas: ['IntGameStates', '213C5A944229FDD9D1D3FBA6EFECE93B', 'Value'],
        html: 'animal-totems-solution-4',
        title: 'Stone 4',
        type: 'dropdown',
        values: [
            { actual: 0, display: 'Whark (0)' },
            { actual: 1, display: 'Ardvark? (1)' },
            { actual: 2, display: 'Mole (2)' },
            { actual: 3, display: 'Sunner (3)' },
            { actual: 4, display: 'Flying Beetle (4)' },
            { actual: 5, display: 'Gaping Fish (5)' },
            { actual: 6, display: 'Anteater (6)' },
            { actual: 7, display: 'Ostrich (7)' },
            { actual: 8, display: 'Tadpole (8)' },
            { actual: 9, display: 'Stork (9)' },
            { actual: 10, display: 'Beetle (10)' },
            { actual: 11, display: 'Moose (11)' },
            { actual: 12, display: 'Alligator (12)' },
            { actual: 13, display: 'Toucan (13)' },
            { actual: 14, display: 'Boar (14)' },
            { actual: 15, display: 'Triangle Fish (15)' },
            { actual: 16, display: 'Praying Beetle (16)' },
            { actual: 17, display: 'Ytram (17)' },
            { actual: 18, display: 'Narwhal (18)' },
            { actual: 19, display: 'Pig (19)' },
            { actual: 20, display: 'Crab (20)' },
            { actual: 21, display: 'Flea (21)' },
            { actual: 22, display: 'Seahorse (22)' },
            { actual: 23, display: 'Shark (23)' }
        ]
    }, {
        gvas: ['IntGameStates', '18E516BA40ABA3943796E08CBF45AE05', 'Value'],
        html: 'animal-totems-solution-5',
        title: 'Stone 5',
        type: 'dropdown',
        values: [
            { actual: 0, display: 'Whark (0)' },
            { actual: 1, display: 'Ardvark? (1)' },
            { actual: 2, display: 'Mole (2)' },
            { actual: 3, display: 'Sunner (3)' },
            { actual: 4, display: 'Flying Beetle (4)' },
            { actual: 5, display: 'Gaping Fish (5)' },
            { actual: 6, display: 'Anteater (6)' },
            { actual: 7, display: 'Ostrich (7)' },
            { actual: 8, display: 'Tadpole (8)' },
            { actual: 9, display: 'Stork (9)' },
            { actual: 10, display: 'Beetle (10)' },
            { actual: 11, display: 'Moose (11)' },
            { actual: 12, display: 'Alligator (12)' },
            { actual: 13, display: 'Toucan (13)' },
            { actual: 14, display: 'Boar (14)' },
            { actual: 15, display: 'Triangle Fish (15)' },
            { actual: 16, display: 'Praying Beetle (16)' },
            { actual: 17, display: 'Ytram (17)' },
            { actual: 18, display: 'Narwhal (18)' },
            { actual: 19, display: 'Pig (19)' },
            { actual: 20, display: 'Crab (20)' },
            { actual: 21, display: 'Flea (21)' },
            { actual: 22, display: 'Seahorse (22)' },
            { actual: 23, display: 'Shark (23)' }
        ]
    }, {
        gvas: ['IntGameStates', '9ACF25A2489D8202A351C2998DE2710E', 'Value'],
        html: 'animal-totems-solution-6',
        title: 'Stone 6',
        type: 'dropdown',
        values: [
            { actual: 0, display: 'Whark (0)' },
            { actual: 1, display: 'Ardvark? (1)' },
            { actual: 2, display: 'Mole (2)' },
            { actual: 3, display: 'Sunner (3)' },
            { actual: 4, display: 'Flying Beetle (4)' },
            { actual: 5, display: 'Gaping Fish (5)' },
            { actual: 6, display: 'Anteater (6)' },
            { actual: 7, display: 'Ostrich (7)' },
            { actual: 8, display: 'Tadpole (8)' },
            { actual: 9, display: 'Stork (9)' },
            { actual: 10, display: 'Beetle (10)' },
            { actual: 11, display: 'Moose (11)' },
            { actual: 12, display: 'Alligator (12)' },
            { actual: 13, display: 'Toucan (13)' },
            { actual: 14, display: 'Boar (14)' },
            { actual: 15, display: 'Triangle Fish (15)' },
            { actual: 16, display: 'Praying Beetle (16)' },
            { actual: 17, display: 'Ytram (17)' },
            { actual: 18, display: 'Narwhal (18)' },
            { actual: 19, display: 'Pig (19)' },
            { actual: 20, display: 'Crab (20)' },
            { actual: 21, display: 'Flea (21)' },
            { actual: 22, display: 'Seahorse (22)' },
            { actual: 23, display: 'Shark (23)' }
        ]
    }]
}, {
    html: 'slider-solution',
    title: 'Fire Marble Slider Solution',
    description: '',
    children: [{
        gvas: ['IntGameStates', 'E5FF19854DC3712FB898B98AA6A79183', 'Value'],
        html: 'fire-marble-slider-solution-red',
        title: 'Position 5',
        type: 'dropdown',
        values: [
            { actual: 1, display: '0' },
            { actual: 2, display: '1' },
            { actual: 3, display: '2' },
            { actual: 4, display: '3' },
            { actual: 5, display: '4' },
            { actual: 6, display: '5' },
            { actual: 7, display: '6' },
            { actual: 8, display: '7' },
            { actual: 9, display: '8' },
            { actual: 10, display: '9' },
            { actual: 11, display: '10' },
            { actual: 12, display: '11' },
            { actual: 13, display: '12' },
            { actual: 14, display: '13' },
            { actual: 15, display: '14' },
            { actual: 16, display: '15' },
            { actual: 17, display: '16' },
            { actual: 18, display: '17' },
            { actual: 19, display: '18' },
            { actual: 20, display: '19' },
            { actual: 21, display: '20' },
            { actual: 22, display: '21' },
            { actual: 23, display: '22' },
            { actual: 24, display: '23' },
            { actual: 25, display: '24' },
            { actual: 26, display: '25' }
        ]
    }, {
        gvas: ['IntGameStates', '6AEEE82148E150FC076018B62F6DB6EC', 'Value'],
        html: 'fire-marble-slider-solution-orange',
        title: 'Position 4',
        type: 'dropdown',
        values: [
            { actual: 1, display: '0' },
            { actual: 2, display: '1' },
            { actual: 3, display: '2' },
            { actual: 4, display: '3' },
            { actual: 5, display: '4' },
            { actual: 6, display: '5' },
            { actual: 7, display: '6' },
            { actual: 8, display: '7' },
            { actual: 9, display: '8' },
            { actual: 10, display: '9' },
            { actual: 11, display: '10' },
            { actual: 12, display: '11' },
            { actual: 13, display: '12' },
            { actual: 14, display: '13' },
            { actual: 15, display: '14' },
            { actual: 16, display: '15' },
            { actual: 17, display: '16' },
            { actual: 18, display: '17' },
            { actual: 19, display: '18' },
            { actual: 20, display: '19' },
            { actual: 21, display: '20' },
            { actual: 22, display: '21' },
            { actual: 23, display: '22' },
            { actual: 24, display: '23' },
            { actual: 25, display: '24' },
            { actual: 26, display: '25' }
        ]
    }, {
        gvas: ['IntGameStates', '65C8738A4013B3A7115CBA97984450E4', 'Value'],
        html: 'fire-marble-slider-solution-green',
        title: 'Position 3',
        type: 'dropdown',
        values: [
            { actual: -1, display: '0' },
            { actual: 0, display: '1' },
            { actual: 1, display: '2' },
            { actual: 2, display: '3' },
            { actual: 3, display: '4' },
            { actual: 4, display: '5' },
            { actual: 5, display: '6' },
            { actual: 6, display: '7' },
            { actual: 7, display: '8' },
            { actual: 8, display: '9' },
            { actual: 9, display: '10' },
            { actual: 10, display: '11' },
            { actual: 11, display: '12' },
            { actual: 12, display: '13' },
            { actual: 13, display: '14' },
            { actual: 14, display: '15' },
            { actual: 15, display: '16' },
            { actual: 16, display: '17' },
            { actual: 17, display: '18' },
            { actual: 18, display: '19' },
            { actual: 19, display: '20' },
            { actual: 20, display: '21' },
            { actual: 21, display: '22' },
            { actual: 22, display: '23' },
            { actual: 23, display: '24' },
            { actual: 24, display: '25' }
        ]
    }, {
        gvas: ['IntGameStates', '066A9CD44D13FF9309BFF4AEAD549AB4', 'Value'],
        html: 'fire-marble-slider-solution-blue',
        title: 'Position 2',
        type: 'dropdown',
        values: [
            { actual: 1, display: '0' },
            { actual: 2, display: '1' },
            { actual: 3, display: '2' },
            { actual: 4, display: '3' },
            { actual: 5, display: '4' },
            { actual: 6, display: '5' },
            { actual: 7, display: '6' },
            { actual: 8, display: '7' },
            { actual: 9, display: '8' },
            { actual: 10, display: '9' },
            { actual: 11, display: '10' },
            { actual: 12, display: '11' },
            { actual: 13, display: '12' },
            { actual: 14, display: '13' },
            { actual: 15, display: '14' },
            { actual: 16, display: '15' },
            { actual: 17, display: '16' },
            { actual: 18, display: '17' },
            { actual: 19, display: '18' },
            { actual: 20, display: '19' },
            { actual: 21, display: '20' },
            { actual: 22, display: '21' },
            { actual: 23, display: '22' },
            { actual: 24, display: '23' },
            { actual: 25, display: '24' },
            { actual: 26, display: '25' }
        ]
    }, {
        gvas: ['IntGameStates', '140EE7CC4CCF6618DFE02D89559B7516', 'Value'],
        html: 'fire-marble-slider-solution-violet',
        title: 'Position 1',
        type: 'dropdown',
        values: [
            { actual: 1, display: '0' },
            { actual: 2, display: '1' },
            { actual: 3, display: '2' },
            { actual: 4, display: '3' },
            { actual: 5, display: '4' },
            { actual: 6, display: '5' },
            { actual: 7, display: '6' },
            { actual: 8, display: '7' },
            { actual: 9, display: '8' },
            { actual: 10, display: '9' },
            { actual: 11, display: '10' },
            { actual: 12, display: '11' },
            { actual: 13, display: '12' },
            { actual: 14, display: '13' },
            { actual: 15, display: '14' },
            { actual: 16, display: '15' },
            { actual: 17, display: '16' },
            { actual: 18, display: '17' },
            { actual: 19, display: '18' },
            { actual: 20, display: '19' },
            { actual: 21, display: '20' },
            { actual: 22, display: '21' },
            { actual: 23, display: '22' },
            { actual: 24, display: '23' },
            { actual: 25, display: '24' },
            { actual: 26, display: '25' }
        ]
    }]
}, {
    gvas: ['IntGameStates', '7FF5C77A4666C0B2D86D74A39205DC54', 'Value'],
    title: 'Moiety Cave Solution',
    html: 'moiety-cave-solution-1',
    image: 'moiety-cave.png',
    alt: 'The five possible solutions for the Moiety Cave puzzle.',
    type: 'dropdown',
    values: [0, 1, 2, 3, 4]
}, {
    gvas: ['IntGameStates', '22BA75C942980718DFBBE29C89486F91', 'Value'],
    html: 'temple-main-door',
    title: 'Temple Main Door',
    type: 'dropdown',
    values: [
        { actual: 0, display: 'Closed' },
        { actual: 1, display: 'Open' }
    ]
}]